//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClcAgentModel", "FK_UserAndRoleXLink_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CST_150_Activity_6.FcsAgentWebApp.FcsuAgent.BuisnessObjects_try.Role), "UserAndRoleXLink", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CST_150_Activity_6.FcsAgentWebApp.FcsuAgent.BuisnessObjects_try.UserAndRoleXLink), true)]
[assembly: EdmRelationshipAttribute("ClcAgentModel", "FK_UserAndRoleXLink_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CST_150_Activity_6.FcsAgentWebApp.FcsuAgent.BuisnessObjects_try.User), "UserAndRoleXLink", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CST_150_Activity_6.FcsAgentWebApp.FcsuAgent.BuisnessObjects_try.UserAndRoleXLink), true)]

#endregion

namespace CST_150_Activity_6.FcsAgentWebApp.FcsuAgent.BuisnessObjects_try
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClcAgentEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClcAgentEntities object using the connection string found in the 'ClcAgentEntities' section of the application configuration file.
        /// </summary>
        public ClcAgentEntities() : base("name=ClcAgentEntities", "ClcAgentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClcAgentEntities object.
        /// </summary>
        public ClcAgentEntities(string connectionString) : base(connectionString, "ClcAgentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClcAgentEntities object.
        /// </summary>
        public ClcAgentEntities(EntityConnection connection) : base(connection, "ClcAgentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<member> members
        {
            get
            {
                if ((_members == null))
                {
                    _members = base.CreateObjectSet<member>("members");
                }
                return _members;
            }
        }
        private ObjectSet<member> _members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<policy> policies
        {
            get
            {
                if ((_policies == null))
                {
                    _policies = base.CreateObjectSet<policy>("policies");
                }
                return _policies;
            }
        }
        private ObjectSet<policy> _policies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserAndRoleXLink> UserAndRoleXLinks
        {
            get
            {
                if ((_UserAndRoleXLinks == null))
                {
                    _UserAndRoleXLinks = base.CreateObjectSet<UserAndRoleXLink>("UserAndRoleXLinks");
                }
                return _UserAndRoleXLinks;
            }
        }
        private ObjectSet<UserAndRoleXLink> _UserAndRoleXLinks;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomembers(member member)
        {
            base.AddObject("members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the policies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopolicies(policy policy)
        {
            base.AddObject("policies", policy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserAndRoleXLinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserAndRoleXLinks(UserAndRoleXLink userAndRoleXLink)
        {
            base.AddObject("UserAndRoleXLinks", userAndRoleXLink);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClcAgentModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new member object.
        /// </summary>
        /// <param name="cst_num">Initial value of the cst_num property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static member Createmember(global::System.Int32 cst_num, global::System.String email)
        {
            member member = new member();
            member.cst_num = cst_num;
            member.email = email;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cst_num
        {
            get
            {
                return _cst_num;
            }
            set
            {
                if (_cst_num != value)
                {
                    Oncst_numChanging(value);
                    ReportPropertyChanging("cst_num");
                    _cst_num = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cst_num");
                    Oncst_numChanged();
                }
            }
        }
        private global::System.Int32 _cst_num;
        partial void Oncst_numChanging(global::System.Int32 value);
        partial void Oncst_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                if (_email != value)
                {
                    OnemailChanging(value);
                    ReportPropertyChanging("email");
                    _email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("email");
                    OnemailChanged();
                }
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClcAgentModel", Name="policy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class policy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new policy object.
        /// </summary>
        /// <param name="policy1">Initial value of the policy1 property.</param>
        /// <param name="agent">Initial value of the agent property.</param>
        /// <param name="cst_num">Initial value of the cst_num property.</param>
        /// <param name="value">Initial value of the value property.</param>
        /// <param name="plantype">Initial value of the plantype property.</param>
        /// <param name="annrate">Initial value of the annrate property.</param>
        /// <param name="ytd_int">Initial value of the ytd_int property.</param>
        /// <param name="begbal">Initial value of the begbal property.</param>
        public static policy Createpolicy(global::System.String policy1, global::System.String agent, global::System.Int32 cst_num, global::System.Decimal value, global::System.String plantype, global::System.Decimal annrate, global::System.Decimal ytd_int, global::System.Decimal begbal)
        {
            policy policy = new policy();
            policy.policy1 = policy1;
            policy.agent = agent;
            policy.cst_num = cst_num;
            policy.value = value;
            policy.plantype = plantype;
            policy.annrate = annrate;
            policy.ytd_int = ytd_int;
            policy.begbal = begbal;
            return policy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String policy1
        {
            get
            {
                return _policy1;
            }
            set
            {
                if (_policy1 != value)
                {
                    Onpolicy1Changing(value);
                    ReportPropertyChanging("policy1");
                    _policy1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("policy1");
                    Onpolicy1Changed();
                }
            }
        }
        private global::System.String _policy1;
        partial void Onpolicy1Changing(global::System.String value);
        partial void Onpolicy1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String agent
        {
            get
            {
                return _agent;
            }
            set
            {
                if (_agent != value)
                {
                    OnagentChanging(value);
                    ReportPropertyChanging("agent");
                    _agent = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("agent");
                    OnagentChanged();
                }
            }
        }
        private global::System.String _agent;
        partial void OnagentChanging(global::System.String value);
        partial void OnagentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cst_num
        {
            get
            {
                return _cst_num;
            }
            set
            {
                if (_cst_num != value)
                {
                    Oncst_numChanging(value);
                    ReportPropertyChanging("cst_num");
                    _cst_num = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cst_num");
                    Oncst_numChanged();
                }
            }
        }
        private global::System.Int32 _cst_num;
        partial void Oncst_numChanging(global::System.Int32 value);
        partial void Oncst_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal value
        {
            get
            {
                return _value;
            }
            set
            {
                if (_value != value)
                {
                    OnvalueChanging(value);
                    ReportPropertyChanging("value");
                    _value = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("value");
                    OnvalueChanged();
                }
            }
        }
        private global::System.Decimal _value;
        partial void OnvalueChanging(global::System.Decimal value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String plantype
        {
            get
            {
                return _plantype;
            }
            set
            {
                if (_plantype != value)
                {
                    OnplantypeChanging(value);
                    ReportPropertyChanging("plantype");
                    _plantype = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("plantype");
                    OnplantypeChanged();
                }
            }
        }
        private global::System.String _plantype;
        partial void OnplantypeChanging(global::System.String value);
        partial void OnplantypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal annrate
        {
            get
            {
                return _annrate;
            }
            set
            {
                if (_annrate != value)
                {
                    OnannrateChanging(value);
                    ReportPropertyChanging("annrate");
                    _annrate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("annrate");
                    OnannrateChanged();
                }
            }
        }
        private global::System.Decimal _annrate;
        partial void OnannrateChanging(global::System.Decimal value);
        partial void OnannrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ytd_int
        {
            get
            {
                return _ytd_int;
            }
            set
            {
                if (_ytd_int != value)
                {
                    Onytd_intChanging(value);
                    ReportPropertyChanging("ytd_int");
                    _ytd_int = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ytd_int");
                    Onytd_intChanged();
                }
            }
        }
        private global::System.Decimal _ytd_int;
        partial void Onytd_intChanging(global::System.Decimal value);
        partial void Onytd_intChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal begbal
        {
            get
            {
                return _begbal;
            }
            set
            {
                if (_begbal != value)
                {
                    OnbegbalChanging(value);
                    ReportPropertyChanging("begbal");
                    _begbal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("begbal");
                    OnbegbalChanged();
                }
            }
        }
        private global::System.Decimal _begbal;
        partial void OnbegbalChanging(global::System.Decimal value);
        partial void OnbegbalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClcAgentModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="isDisabled">Initial value of the IsDisabled property.</param>
        public static Role CreateRole(global::System.Guid id, global::System.String name, global::System.String description, global::System.Boolean isDisabled)
        {
            Role role = new Role();
            role.Id = id;
            role.Name = name;
            role.Description = description;
            role.IsDisabled = isDisabled;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDisabled
        {
            get
            {
                return _IsDisabled;
            }
            set
            {
                OnIsDisabledChanging(value);
                ReportPropertyChanging("IsDisabled");
                _IsDisabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDisabled");
                OnIsDisabledChanged();
            }
        }
        private global::System.Boolean _IsDisabled;
        partial void OnIsDisabledChanging(global::System.Boolean value);
        partial void OnIsDisabledChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClcAgentModel", "FK_UserAndRoleXLink_Role", "UserAndRoleXLink")]
        public EntityCollection<UserAndRoleXLink> UserAndRoleXLinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserAndRoleXLink>("ClcAgentModel.FK_UserAndRoleXLink_Role", "UserAndRoleXLink");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserAndRoleXLink>("ClcAgentModel.FK_UserAndRoleXLink_Role", "UserAndRoleXLink", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClcAgentModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isDisabled">Initial value of the IsDisabled property.</param>
        public static User CreateUser(global::System.Guid id, global::System.Boolean isDisabled)
        {
            User user = new User();
            user.Id = id;
            user.IsDisabled = isDisabled;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDisabled
        {
            get
            {
                return _IsDisabled;
            }
            set
            {
                OnIsDisabledChanging(value);
                ReportPropertyChanging("IsDisabled");
                _IsDisabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDisabled");
                OnIsDisabledChanged();
            }
        }
        private global::System.Boolean _IsDisabled;
        partial void OnIsDisabledChanging(global::System.Boolean value);
        partial void OnIsDisabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgentNumber
        {
            get
            {
                return _AgentNumber;
            }
            set
            {
                OnAgentNumberChanging(value);
                ReportPropertyChanging("AgentNumber");
                _AgentNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AgentNumber");
                OnAgentNumberChanged();
            }
        }
        private global::System.String _AgentNumber;
        partial void OnAgentNumberChanging(global::System.String value);
        partial void OnAgentNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClcAgentModel", "FK_UserAndRoleXLink_User", "UserAndRoleXLink")]
        public EntityCollection<UserAndRoleXLink> UserAndRoleXLinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserAndRoleXLink>("ClcAgentModel.FK_UserAndRoleXLink_User", "UserAndRoleXLink");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserAndRoleXLink>("ClcAgentModel.FK_UserAndRoleXLink_User", "UserAndRoleXLink", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClcAgentModel", Name="UserAndRoleXLink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserAndRoleXLink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserAndRoleXLink object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static UserAndRoleXLink CreateUserAndRoleXLink(global::System.Guid id, global::System.Guid userId, global::System.Guid roleId)
        {
            UserAndRoleXLink userAndRoleXLink = new UserAndRoleXLink();
            userAndRoleXLink.Id = id;
            userAndRoleXLink.UserId = userId;
            userAndRoleXLink.RoleId = roleId;
            return userAndRoleXLink;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Guid _RoleId;
        partial void OnRoleIdChanging(global::System.Guid value);
        partial void OnRoleIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClcAgentModel", "FK_UserAndRoleXLink_Role", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ClcAgentModel.FK_UserAndRoleXLink_Role", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ClcAgentModel.FK_UserAndRoleXLink_Role", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ClcAgentModel.FK_UserAndRoleXLink_Role", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("ClcAgentModel.FK_UserAndRoleXLink_Role", "Role", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClcAgentModel", "FK_UserAndRoleXLink_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ClcAgentModel.FK_UserAndRoleXLink_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ClcAgentModel.FK_UserAndRoleXLink_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ClcAgentModel.FK_UserAndRoleXLink_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ClcAgentModel.FK_UserAndRoleXLink_User", "User", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
